"""empty message

Revision ID: 1cd4e5b01d0f
Revises: 4a0947050e07
Create Date: 2017-04-17 15:48:51.227699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd4e5b01d0f'
down_revision = '4a0947050e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_list', sa.Column('desc', sa.String(length=200), nullable=True))
    op.add_column('wish_list', sa.Column('title', sa.String(length=20), nullable=True))
    op.add_column('wish_list', sa.Column('webadd', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_list', 'webadd')
    op.drop_column('wish_list', 'title')
    op.drop_column('wish_list', 'desc')
    # ### end Alembic commands ###
